name: Prettier code formatter
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier Check 🔎
        run: echo "Prettier check disabled"
        
